title: Michael Sabzevari's Page
author: Michael Sabzevari
email: michaelsabzevari@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Student at General Assembly, aiming to become a web developer.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
